import React, { useState } from 'react';
import { X, Sparkles, Copy, Check, ShieldAlert, MapPin } from 'lucide-react';

export default function BriefingModal({ briefing, onClose }) {
  const [copied, setCopied] = useState(false);

  if (!briefing) return null;

  const handleCopy = () => {
    const text = `
=== ${briefing.title} ===
Severity: ${briefing.severity}
Target Node: ${briefing.target_id}
Location: ${briefing.location}

${briefing.topology_note}

ACTION PLAN:
${briefing.action_plan.join('\n')}

SAFETY PROTOCOL:
${briefing.safety_warning}

Generated by: ${briefing.generated_by}
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100vw',
      height: '100vh',
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      backdropFilter: 'blur(8px)',
      zIndex: 2000,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center'
    }}>
      <div className="glass-panel" style={{
        width: '580px',
        maxHeight: '85vh',
        overflowY: 'auto',
        padding: '24px',
        borderRadius: '24px',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        boxShadow: '0 20px 50px rgba(0, 0, 0, 0.6)'
      }}>
        {/* Modal Header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{
              width: '32px',
              height: '32px',
              borderRadius: '8px',
              background: 'var(--accent-primary)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}>
              <Sparkles size={18} color="#ffffff" />
            </div>
            <div>
              <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-main)' }}>AI Crew Dispatch Briefing</h3>
              <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Generated for Field Lineman Crew</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', padding: '4px' }}
          >
            <X size={20} />
          </button>
        </div>

        {/* Title & Severity */}
        <div style={{ background: 'var(--bg-secondary)', padding: '16px', borderRadius: '16px', border: '1px solid var(--border-color)' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
            <span className="badge badge-red">{briefing.severity} SEVERITY</span>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '4px' }}>
              <MapPin size={14} color="var(--accent-primary)" />
              {briefing.location}
            </span>
          </div>
          <h4 style={{ fontSize: '0.95rem', fontWeight: 600, color: 'var(--text-main)' }}>{briefing.title}</h4>
        </div>

        {/* Topology Note (MST Imputed Warning) */}
        <div style={{
          background: briefing.is_imputed ? 'rgba(245, 158, 11, 0.1)' : 'rgba(16, 185, 129, 0.1)',
          border: briefing.is_imputed ? '1px solid rgba(245, 158, 11, 0.2)' : '1px solid rgba(16, 185, 129, 0.2)',
          borderRadius: '16px',
          padding: '12px',
          fontSize: '0.85rem',
          color: briefing.is_imputed ? '#f97316' : '#22c55e',
          lineHeight: '1.4'
        }}>
          {briefing.topology_note}
        </div>

        {/* Action Plan */}
        <div>
          <h4 style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', uppercase: 'true', marginBottom: '8px' }}>
            FIELD ACTION PLAN:
          </h4>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '6px', fontSize: '0.85rem' }}>
            {briefing.action_plan.map((step, i) => (
              <li key={i} style={{ background: 'rgba(255, 255, 255, 0.03)', padding: '8px 12px', borderRadius: '6px', borderLeft: '3px solid var(--accent-primary)' }}>
                {step}
              </li>
            ))}
          </ul>
        </div>

        {/* Safety Protocol */}
        <div style={{
          background: 'rgba(239, 68, 68, 0.1)',
          border: '1px solid rgba(239, 68, 68, 0.2)',
          borderRadius: '16px',
          padding: '12px',
          display: 'flex',
          alignItems: 'flex-start',
          gap: '10px'
        }}>
          <ShieldAlert size={20} color="#ef4444" style={{ flexShrink: 0, marginTop: '2px' }} />
          <div style={{ fontSize: '0.8rem', color: '#fca5a5', lineHeight: '1.4' }}>
            <strong>SAFETY WARNING:</strong> {briefing.safety_warning}
          </div>
        </div>

        {/* Footer Actions */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingTop: '8px', borderTop: '1px solid var(--border-color)' }}>
          <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>{briefing.generated_by}</span>
          <button
            onClick={handleCopy}
            style={{
              background: copied ? 'var(--accent-success)' : 'var(--accent-primary)',
              border: 'none',
              color: '#ffffff',
              borderRadius: '6px',
              padding: '8px 16px',
              fontSize: '0.8rem',
              fontWeight: 600,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied to Clipboard!' : 'Copy Dispatch Briefing'}
          </button>
        </div>
      </div>
    </div>
  );
}
