from pydantic import BaseModel, Field
from datetime import datetime

class TelemetryEvent(BaseModel):
    device_id: str = Field(..., description="The ID of the IoT device sending the event")
    pole_id: str = Field(..., description="The ID of the pole the device is mounted on")
    event: str = Field(..., description="The type of event, e.g., 'power_lost' or 'power_restored'")
    energized: bool = Field(..., description="The physical state of the wire (True = live, False = dead)")
    ts: datetime = Field(..., description="The ISO8601 timestamp generated by the device clock")
    seq: int = Field(..., description="The device's internal monotonically increasing sequence counter")
    battery_mv: int = Field(..., description="Device battery voltage in millivolts")
    rssi: int = Field(..., description="Signal strength indicator")
    fw: str = Field(..., description="Firmware version string")

class FaultResponse(BaseModel):
    status: str
    message: str
    faults_detected: int
